require 'rubygems'
require 'bundler'

Bundler.setup

require 'cucumber/rake/task'
require 'rspec'
require 'rspec/core/rake_task'

SPEC_SUITES = [
	{
		:id=>:ecp,
		:title=>'ecp',
		:padrao=>'spec/lib/ecp/*_spec.rb'
	}
]

namespace :cucumber do

	Cucumber::Rake::Task.new(:wip) do |t|
		t.cucumber_opts = "features --tags @wip"
	end
end

namespace :spec do
	namespace :suite do
		SPEC_SUITES.each do |suite|
			desc "Run all specs in #{suite[:title]} spec suite"
			Rspec::Core::RakeTask.new(suite[:id]) do |t|
				t.pattern = suite[:padrao]
			end
		end

	end
end
